name: Test pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md

  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./main

    steps:
      - uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout another codebase
        uses: actions/checkout@v4
        with:
          repository: shakirshakiel/grafana-metrics-analyser
          token: ${{ secrets.GH_PAT }}
          ref: main
          path: secondary

      - name: Print branch name
        run: |
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}

      - name: List directories
        run: |
          ls -l
        
      - name: List directories from parent
        run: |
          ls -l
          ls -l main
          ls -l secondary
        working-directory: .