name: Test pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md

  workflow_dispatch:

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate TF docs
        uses: terraform-docs/gh-actions@v1.4.0
        with:
          working-dir: modules/
          recursive: true
          fail-on-diff: true
