name: Test pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md

  workflow_dispatch:

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout another codebase
        uses: actions/checkout@v4
        with:
          name: shakirshakiel/devbox-environments
          ref: refs/head/development

      - name: Print branch name
        run: "echo ${{ github.head_ref }}"

      - name: List directories
        run: "ls -l"        